contentful/vercel-nextjs-toolkit

release.config.json
- Add distribution configuration for semantic release
=> Add release config

lib/handlers/app-router.spec.ts, lib/handlers/app-router.ts
Recently we updated this handler to obtain the protection bypass token from the payload of the `_vercel_jwt` JWT token cookie. This cookie is set whenever a user successfully passes `x-vercel-protection-bypass=your-generated-secret` _and_ `x-vercel-set-bypass-cookie=samesitenone` in the query. The change was required because Vercel automatically strips those query params from the URL on redirect and we no longer were able to process them in that handler.
When we made this change we removed any support whatsoever for our handler to parse `x-vercel-protection-bypass` from the query. But this made our implementation more brittle, especially if Vercel ever changes any implentation details of the cookie.
So this PR reintroduces `x-vercel-protection-bypass` as an alternative and will defer to …
=> feat: support x-vercel-protection-bypass in query as fallback

package.json, vite.config.ts
=> Update missing export

lib/app-router/handlers/app-router.spec.ts, lib/app-router/handlers/app-router.ts, lib/app-router/helpers/is-next-api-request.ts, vite.config.ts
=> chore: [] - refactor handler missing context

README.md
We need some basic info in our README
See the file!
=> chore: update README with more documentation

README.md
=> chore: add package status

package.json, vite.config.ts
- fixes configuration for new release, reverts exports
=> fix: [] - Fix bundler config

release.config.json
- adds missing semantic release plugins
=> fix: [] - Add missing semantic plugins

package.json
- manually bumps version to re-sync semantic release
=> fix: [] - Bump version

package.json
=> fix: [] - add missing config

package-lock.json, vite.config.ts
=> fix: build for ssr

package-lock.json, package.json, release.config.json
- adds missing semantic release packages to kick off bot changes
=> fix: add semantic release packages

package.json
- adds missing branch configuration for releaser
=> fix: add missing branch configuration for releaser

package.json
- bumps package version to work with bot
=> fix: bump package version

package.json
- syncs releases to kickoff automation bot
=> fix: [] - sync releases

README.md
Just a it of clean up to streamline the docs
=> chore: minor README cleanup

lib/utils/index.ts
- tests publishing new version
=> chore: linting & publish new version test

release.config.json
=> fix: add changelog, trigger release

.contentful/vault-secrets.yaml, .releaserc.json
=> fix: fix config

.github/workflows/release-package.yml
=> fix: update workflow

.github/dependabot.yml
=> feat: setup basic dependabot config [INTEG-2141]
